#!/usr/bin/env bash
# script to checking the command line argument

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# variable the Arguments

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4


# checking the host key
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Checking the success of the transfer
if [ $? -eq 0 ]
then
  echo "FILE SUCCESSFULL"
else
  echo "FILE FAILED"
fi
